### ISSUE TITLE
Can't destroy dinghy VM

### ISSUE THREAD

**Issue by Ghazgkull** [codekitchen/dinghy#220] opened 2016-12-14 00:33 UTC
Just tried destroying my dinghy VM and it failed in a couple ways:

1. If the VM is stopped, running `dinghy destroy` fails with:
```
$ dinghy destroy
Stopping the FsEvents daemon
Stopping the dinghy VM...
Machine "dinghy" is already stopped.
/usr/local/Cellar/dinghy/HEAD-b584148/cli/dinghy/system.rb:11:in `system': Failure calling `docker-machine stop dinghy` (System::Failure)
	from /usr/local/Cellar/dinghy/HEAD-b584148/cli/dinghy/machine.rb:126:in `system'
	from /usr/local/Cellar/dinghy/HEAD-b584148/cli/dinghy/machine.rb:106:in `halt'
	from /usr/local/Cellar/dinghy/HEAD-b584148/cli/cli.rb:124:in `halt'
	from /usr/local/Cellar/dinghy/HEAD-b584148/cli/cli.rb:143:in `destroy'
	from /usr/local/Cellar/dinghy/HEAD-b584148/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/HEAD-b584148/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/HEAD-b584148/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/HEAD-b584148/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
```
2. If dinghy is running, `dinghy destroy` successfully stops the VM, but then quietly exits without deleting the image.
```
$ dinghy destroy
Stopping the FsEvents daemon
Stopping the dinghy VM...
Stopping NFS daemon, this will require sudo
$ docker-machine ls
NAME     ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
dinghy   -        virtualbox   Stopped                 Unknown  
```

In order to work around the problem, we used `docker-machine rm dinghy`.

**Comment by Ghazgkull** [comment] 2016-12-14 00:42
Note that I'm up to date with the latest home-brew packages. e.g. Dinghy 4.4.2

**Comment by codekitchen** [comment] 2016-12-14 17:52
I'm unable to reproduce either scenario in Dinghy 4.4.2, but I can reproduce on the latest master -- did you `brew install --HEAD dinghy` at some point by chance? I should set that up to report a different version number.

I'll look into why this is happening on master, there's only been a couple commits so I'm sure it's related to my error reporting modifications.

**Comment by codekitchen** [comment] 2016-12-14 21:17
OK this is fixed on master, and I've modified the homebrew tap to give `dinghy version` a better version identifier when installing from HEAD rather than using the last release version.

**Closed by codekitchen** 2016-12-14 21:17 UTC
