### ISSUE TITLE
NFS mounting is working, but produces error message

### ISSUE THREAD

**Issue by pinnokio** [codekitchen/dinghy#106] opened 2015-11-13 13:58 UTC
Dinghy version: **4.0.7**
OS: Mac OS X 10.11.1

```
dinghy up
```
produces error output

```
NFS failed to run
details available in log file: /usr/local/Cellar/dinghy/HEAD/local/var/dinghy-NFS.output
```

NFS mounting is working, I double checked

**/usr/local/Cellar/dinghy/HEAD/local/var/dinghy-NFS.output** contents
```
/Users/pinnokio/.gem/ruby/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
        from /Users/pinnokio/.gem/ruby/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
        from /Users/pinnokio/.gem/ruby/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:58:in `inspect'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:41:in `vm_ip'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:37:in `host_ip'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/unfs.rb:102:in `command'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/daemon.rb:72:in `run'
        from /usr/local/Cellar/dinghy/HEAD/cli/daemons/lib/daemons/application.rb:264:in `call'
        from /usr/local/Cellar/dinghy/HEAD/cli/daemons/lib/daemons/application.rb:264:in `block in start_proc'
        from /usr/local/Cellar/dinghy/HEAD/cli/daemons/lib/daemons/daemonize.rb:84:in `call'
        from /usr/local/Cellar/dinghy/HEAD/cli/daemons/lib/daemons/daemonize.rb:84:in `call_as_daemon'
        from /usr/local/Cellar/dinghy/HEAD/cli/daemons/lib/daemons/application.rb:268:in `start_proc'
        from /usr/local/Cellar/dinghy/HEAD/cli/daemons/lib/daemons/application.rb:294:in `start'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/daemon.rb:64:in `start'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/daemon.rb:9:in `up'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/unfs.rb:28:in `up'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:186:in `nfs'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
        from /usr/local/Cellar/dinghy/HEAD/bin/_dinghy_command:6:in `<main>'
```

**Comment by codekitchen** [comment] 2015-11-19 19:32
what did you do to verify that NFS is working? depending on where in the process it failed, you might still see the shared dir in the VM, but it'll be running over virtualbox/vmware built-in sharing instead of NFS, so it could be misleading.

The best way to be sure is to run `dinghy ssh mount|grep nfs` and you should see the NFS share mount information.

This errors sounds like `docker-machine inspect dinghy` failed when running as root, which is actually probably going to be a common problem now that I think about it. I may want to just pass the required data to the NFS daemon directly instead.

**Comment by jamesob** [comment] 2015-11-20 18:42
Seeing this as well:
```
c10309itloaner:getdocker itloaner$ dinghy halt
Stopping NFS daemon, this will require sudo
Password:
c10309itloaner:getdocker itloaner$ dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
/usr/local/Cellar/dinghy/4.0.7/cli/dinghy/unfs.rb:25:in `sleep': execution expired (Timeout::Error)
	from /usr/local/Cellar/dinghy/4.0.7/cli/dinghy/unfs.rb:25:in `block in wait_for_unfs'
	from /usr/local/Cellar/dinghy/4.0.7/cli/dinghy/unfs.rb:22:in `wait_for_unfs'
	from /usr/local/Cellar/dinghy/4.0.7/cli/dinghy/unfs.rb:18:in `up'
	from /usr/local/Cellar/dinghy/4.0.7/cli/cli.rb:185:in `start_services'
	from /usr/local/Cellar/dinghy/4.0.7/cli/cli.rb:78:in `up'
	from /usr/local/Cellar/dinghy/4.0.7/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.0.7/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.0.7/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.0.7/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:6:in `<main>'
```

and it doesn't appear that NFS is actually running:

```
c10309itloaner:getdocker itloaner$ dinghy status
  VM: running
 NFS: not running
FSEV: running
 DNS: not running
HTTP: not running
```

However as reported above, mounted volumes are working properly in containers. We should definitely resolve the larger problem as to why NFS mounting fails.

**Comment by jamesob** [comment] 2015-11-20 18:48
FWIW, I'm able to run `sudo docker-machine inspect dinghy` without error:

```
c10309itloaner:getdocker itloaner$ sudo docker-machine inspect dinghy
Password:
{
    "ConfigVersion": 3,
    "Driver": {
        "VBoxManager": {},
        "IPAddress": "192.168.99.100",
        "SSHUser": "docker",
        "SSHPort": 50910,
        "MachineName": "dinghy",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "StorePath": "/Users/itloaner/.docker/machine",
        "CPU": 1,
        "Memory": 2048,
        "DiskSize": 20000,
        "Boot2DockerURL": "",
        "Boot2DockerImportVM": "",
        "HostOnlyCIDR": "192.168.99.1/24",
        "HostOnlyNicType": "82540EM",
        "HostOnlyPromiscMode": "deny",
        "NoShare": false
    },
    "DriverName": "virtualbox",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [],
            "Ipv6": false,
            "InsecureRegistry": [],
            "Labels": [],
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": true,
            "RegistryMirror": [],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Image": "swarm:latest",
            "Strategy": "spread",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": []
        },
        "AuthOptions": {
            "CertDir": "/Users/itloaner/.docker/machine/certs",
            "CaCertPath": "/Users/itloaner/.docker/machine/certs/ca.pem",
            "CaPrivateKeyPath": "/Users/itloaner/.docker/machine/certs/ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/Users/itloaner/.docker/machine/machines/dinghy/server.pem",
            "ServerKeyPath": "/Users/itloaner/.docker/machine/machines/dinghy/server-key.pem",
            "ClientKeyPath": "/Users/itloaner/.docker/machine/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "/Users/itloaner/.docker/machine/certs/cert.pem",
            "StorePath": "/Users/itloaner/.docker/machine/machines/dinghy"
        }
    },
    "Name": "dinghy",
    "RawDriver": "eyJWQm94TWFuYWdlciI6e30sIklQQWRkcmVzcyI6IjE5Mi4xNjguOTkuMTAwIiwiU1NIVXNlciI6ImRvY2tlciIsIlNTSFBvcnQiOjUwOTEwLCJNYWNoaW5lTmFtZSI6ImRpbmdoeSIsIlN3YXJtTWFzdGVyIjpmYWxzZSwiU3dhcm1Ib3N0IjoidGNwOi8vMC4wLjAuMDozMzc2IiwiU3dhcm1EaXNjb3ZlcnkiOiIiLCJTdG9yZVBhdGgiOiIvVXNlcnMvaXRsb2FuZXIvLmRvY2tlci9tYWNoaW5lIiwiQ1BVIjoxLCJNZW1vcnkiOjIwNDgsIkRpc2tTaXplIjoyMDAwMCwiQm9vdDJEb2NrZXJVUkwiOiIiLCJCb290MkRvY2tlckltcG9ydFZNIjoiIiwiSG9zdE9ubHlDSURSIjoiMTkyLjE2OC45OS4xLzI0IiwiSG9zdE9ubHlOaWNUeXBlIjoiODI1NDBFTSIsIkhvc3RPbmx5UHJvbWlzY01vZGUiOiJkZW55IiwiTm9TaGFyZSI6ZmFsc2V9"
}
```

**Comment by markoshust** [comment] 2015-12-28 19:53
This happens randomly for me as well. Rebooting my host machine fixes it (temporarily, until it happens again ).

**Comment by codekitchen** [comment] 2016-01-04 16:31
A lot of the issues with this are because launchd reports success even if the daemon fails to launch (apparently this is by design). Because of all the issues with using/abusing launchd the way we were, we've moved to our own daemon management code in the newest v4.1.0 release of dinghy. I'm going to close this, we'll handle any similar problems on the newest release as a new issue.

**Closed by codekitchen** 2016-01-04 16:31 UTC

**Comment by hgajjar-sessiondigital** [comment] 2016-10-11 08:40
Dinghy 4.4.1
Mac OS Sierra

I'm facing this issue after upgrading to Mac OS Sierra, it was working without any error before in El Capitan.

It seems like the issue is random, when I first try to start dinghy after system boot, it fails with below error message, but when I try to restart, it works.

`/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /usr/local/Cellar/dinghy/4.4.1/cli/dinghy/machine.rb:81:in `inspect'
	from /usr/local/Cellar/dinghy/4.4.1/cli/dinghy/machine.rb:85:in `inspect_driver'
	from /usr/local/Cellar/dinghy/4.4.1/cli/dinghy/machine.rb:52:in `vm_ip'
	from /usr/local/Cellar/dinghy/4.4.1/cli/dinghy/check_env.rb:25:in `expected'
	from /usr/local/Cellar/dinghy/4.4.1/cli/dinghy/check_env.rb:37:in `set?'
	from /usr/local/Cellar/dinghy/4.4.1/cli/dinghy/check_env.rb:11:in `run'
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:104:in `status'
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:229:in `start_services'
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:79:in `up'
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:133:in `restart'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'`

However, I'm able to run `docker-machine inspect dinghy 2>/dev/null` without any issue.

**Comment by codekitchen** [comment] 2016-10-11 15:25
Please open a new issue
