### ISSUE TITLE
`dinghy halt; dinghy up` Error executing command: ["sudo umount /Users || true"] (Ssh::CommandFailed)

### ISSUE THREAD

**Issue by rosskevin** [codekitchen/dinghy#69] opened 2015-09-16 15:55 UTC
When I do a `dinghy halt` then `dinghy up`.  I receive an error going back up:

```bash
$ dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/kross
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/ssh.rb:23:in `run': Error executing command: ["sudo umount /Users || true"] (Ssh::CommandFailed)
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:76:in `ssh'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:69:in `mount'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:181:in `start_services'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:78:in `up'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
        from /usr/local/bin/_dinghy_command:6:in `<main>'
```

This is repeatable.  Am I supposed to restart services some other way?

**Comment by codekitchen** [comment] 2015-09-16 16:15
Definitely a bug of some sort, looks like I need to beef up the error logging though, there's not a lot of relevant info there.

Can you run `dinghy ssh` to ssh into the VM, and then `sudo umount /Users || true` to repeat that command. That should give more details on what's failing.

**Comment by rosskevin** [comment] 2015-09-16 16:26
I guess I was bluffing when I said it was reproducible.  I'm on a fresh restart (without use), I did an up/halt/up and all is well.  I use it a bit today and try to reproduce and get more info.

**Comment by sja87** [comment] 2015-09-17 12:19
same problem

run after downgrade 5.0.3 to 5.0 and NOT install Extension Pack

**Comment by lukebarton** [comment] 2015-09-22 10:42
Since this isn't an issue on first boot (I'm able to resolve this in a similar fashion), I think this is an issue with shutting something down.

I managed to avoid this once, I think it was because I shut the containers down gracefully first. But it might just have been luck. I haven't tried to reproduce.

**Comment by lukebarton** [comment] 2015-09-22 11:01
If I `dinghy ssh` and run `sudo umount /Users`, the command exits cleanly

**Comment by codekitchen** [comment] 2015-09-22 15:47
That's the correct behavior. It's possible this is a timing issue, trying to ssh in before the machine is ready or something. I'm going to push a new release with more logging around this failure.

I ran halt/up in a loop for about 10 minutes but wasn't able to repro the error on my end, so I'm going to need some help tracking it down.

**Comment by codekitchen** [comment] 2015-09-22 15:54
OK, if anybody wants to try out the prerelease master branch, that has some more logging. Instructions on installing it are in the README: https://github.com/codekitchen/dinghy#prereleases

**Comment by rosskevin** [comment] 2015-10-05 16:57
@codekitchen I just encountered the error.  I reinstalled the master head and it solved the problem.  Here's the console in case we need it later:

```
kross:af_core kross$ dinghy halt
Stopping the FsEvents daemon
exit status 1
Stopping NFS daemon, this will require sudo
Password:
Stopping the DNS daemon
kross:af_core kross$ dinghy status
  VM: saved
 NFS: not running
FSEV: not running
 DNS: not running
HTTP: not running

kross:af_core kross$ dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/kross
umount: can't umount /Users: Invalid argument
mount.nfs: an incorrect mount option was specified
mount: mounting 192.168.99.1:/Users/kross on /Users/kross failed: Device or resource busy
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/ssh.rb:23:in `run': Error executing command: ["sudo mount -t nfs 192.168.99.1:/Users/kross /Users/kross -o nfsvers=3,udp,mountport=19321,port=19321,nolock,hard,intr"] (Ssh::CommandFailed)
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:76:in `ssh'
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:72:in `mount'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:181:in `start_services'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:78:in `up'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:6:in `<main>'

kross:af_core kross$ dinghy halt
Stopping NFS daemon, this will require sudo

kross:af_core kross$ brew reinstall --HEAD https://github.com/codekitchen/dinghy/raw/master/dinghy.rb
######################################################################## 100.0%
==> Reinstalling dinghy
==> Cloning https://github.com/codekitchen/dinghy.git
Updating /Library/Caches/Homebrew/dinghy--git
==> Checking out branch master
==> Caveats
Run `dinghy create` to create the VM, then `dinghy up` to bring up the VM and services.
==> Summary
🍺  /usr/local/Cellar/dinghy/HEAD: 120 files, 704K, built in 3 seconds

kross:af_core kross$ dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Password:
Waiting for NFS daemon...
Mounting NFS /Users/kross
Starting the FsEvents daemon
Starting the DNS daemon
Starting the HTTP proxy
d68431656504ac56306d171db2144466f77f74f913ae842135b07c5c482cc30e
Your environment variables are already set correctly.

kross:af_core kross$ dinghy status
  VM: running
 NFS: running
FSEV: running
 DNS: running
HTTP: running
```

**Comment by thatgibbyguy** [comment] 2015-10-09 21:47
Had this issue a few times on sporadic occasions. After reading this thread I simply ran `dinghy upgrade` and everything seems to be working fun now.

**Comment by vyorkin** [comment] 2015-11-18 01:58
@codekitchen I've just tried the prerelease version and it seems that everything is ok now

**Comment by vyorkin** [comment] 2015-11-18 14:51
works for me with prerelease version

**Comment by codekitchen** [comment] 2015-11-18 16:22
@vyorkin can you paste the output from an instance where it did not work?

**Comment by vyorkin** [comment] 2015-11-18 16:23
yeah, sure
```
~/projects/github/starter-kit master
❯ make up
dinghy up
dinghy already running, restarting...
Stopping the FsEvents daemon
Stopping the dinghy VM...
Password:
Stopping NFS daemon, this will require sudo
Stopping the DNS daemon
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/vyorkin
ssh: connect to host 192.168.99.100 port 22: Operation timed out
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/ssh.rb:23:in `run': Error executing command: ["if [ $(grep -c /Users\\[\\^/\\] /proc/mounts) -gt 0 ]; then sudo umount /Users || true; fi;"] (Ssh::CommandFailed)
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:85:in `ssh'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:78:in `mount'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:223:in `start_services'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:82:in `up'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
        from /usr/local/bin/_dinghy_command:6:in `<main>'
make: *** [up] Error 1
```

**Comment by codekitchen** [comment] 2015-11-18 16:26
Hm yeah it's unable to even ssh to the vm, that makes me even more suspicious of a timing issue. I'll try to find out if `docker-machine start` returns before ssh is available on the vm, we might have to just try in a loop until we can successfully ssh in.

**Comment by codekitchen** [comment] 2015-11-18 16:26
After getting that error, if you try `dinghy ssh` a few seconds later does it succeed?

**Comment by vyorkin** [comment] 2015-11-18 16:27
@codekitchen yes, it succeeded

**Comment by codekitchen** [comment] 2015-11-18 16:27
Definitely a timing issue then. OK. I'll code something up soon.

**Comment by codekitchen** [comment] 2016-02-08 21:24
This _should_ be fixed now that dinghy is using docker-machine's ssh support rather than having its own ssh code. Let's re-open if it pops up again.

**Closed by codekitchen** 2016-02-08 21:24 UTC

**Comment by vyorkin** [comment] 2016-02-08 23:20
cool, thank you!
