### ISSUE TITLE
NFS mounting failed

### ISSUE THREAD

**Issue by joergd** [codekitchen/dinghy#142] opened 2016-02-26 12:06 UTC
I am running dinghy version 4.2.0, docker 1.10.2, and docker-machine 0.6.0 on Mac OS X El Capitaine.

I have a fresh brew and dingy install, and ran dinghy create to create a new machine (using vmware).

I got the "NFS mounting failed" error message, and the log files includes:

    >: cat /usr/local/Cellar/dinghy/4.2.0/local/var/dinghy-NFS.output
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
      from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
      from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/machine.rb:60:in `inspect'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/machine.rb:64:in `inspect_driver'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/machine.rb:39:in `vm_ip'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/machine.rb:35:in `host_ip'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/unfs.rb:102:in `command'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:72:in `run'
      from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:264:in `call'
      from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:264:in `block in start_proc'
      from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/daemonize.rb:84:in `call'
      from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/daemonize.rb:84:in `call_as_daemon'
      from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:268:in `start_proc'
      from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:294:in `start'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:64:in `start'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:9:in `up'
      from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/unfs.rb:28:in `up'
      from /usr/local/Cellar/dinghy/4.2.0/cli/cli.rb:173:in `nfs'
      from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/command.rb:27:in `run'
      from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
      from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor.rb:359:in `dispatch'
      from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/base.rb:440:in `start'
      from /usr/local/Cellar/dinghy/4.2.0/bin/_dinghy_command:6:in `<main>'

**Comment by codekitchen** [comment] 2016-02-26 16:08
This indicates that `docker-machine inspect dinghy` didn't output the expected blob of json data. The wrinkle here is that the NFS daemon has to run as root, so dinghy has to call itself with `sudo` to bump up privileges.

Does `sudo docker-machine inspect dinghy` fail for you as well? I think it might make more sense for dinghy to pass this IP directly to the sub-process rather than calling out to docker-machine while running under a potentially different environment due to the sudo'ing.

**Comment by joergd** [comment] 2016-02-26 19:28
I just get a "Host does not exist: "dinghy"" when I run that command ....

**Comment by codekitchen** [comment] 2016-02-26 20:27
Good to know. Then yeah, something about your `sudo` environment is different and `docker-machine` doesn't work properly on your computer when run under `sudo`. I think avoiding calling out to `docker-machine` during the `sudo` operation is going to be the best fix.

I don't know enough about what may be different in your sudo environment to suggest a workaround in the meantime, unfortunately. But if you can get `sudo docker-machine inspect dinghy` to work, that should fix dinghy as well.

**Comment by joergd** [comment] 2016-02-27 10:15
Ok cool - and if I can’t figure that out - will there be a fix - ie a different way of doing things in the next version of dinghy?

**Comment by codekitchen** [comment] 2016-02-29 16:41
This should be fixed by https://github.com/codekitchen/dinghy/commit/bcacf02bfd1cf4fbb9f1b3aac17934b4673c3721, but I'm unable to verify locally since I can't repro the problem. You can test it out by installing the [dinghy prerelease](https://github.com/codekitchen/dinghy#prereleases).

**Comment by mattbroekhuis** [comment] 2016-02-29 17:32
I re-installed late last night and things started clicking. Not sure if because of that commit or not. issue resolved. Thank you!

**Comment by joergd** [comment] 2016-02-29 18:33
I installed the prelease but get the following error:

    >: dinghy up
    Starting the dinghy VM...
    Starting NFS daemon, this will require sudo
    Password:
    Waiting for NFS daemon...
    Mounting NFS /Users/joerg
    mount: 172.16.52.1:/Users/joerg failed, reason given by server: Permission denied
    mount: mounting 172.16.52.1:/Users/joerg on /Users/joerg failed: Bad file descriptor
    exit status 110
    /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:103:in `ssh': ssh command failed (RuntimeError)
      from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:99:in `mount'
      from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:217:in `start_services'
      from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:85:in `up'
      from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
      from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
      from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
      from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'

**Comment by joergd** [comment] 2016-02-29 18:35
Not sure if this helps .... https://github.com/docker/machine/issues/3127#issuecomment-190301243

**Comment by codekitchen** [comment] 2016-02-29 19:32
Hm something more is going on, this is unrelated to the previous error. Looks like NFS in the linux VM was refused by the NFS server on the host. Can you paste the output of these bash commands after running `dinghy up`:

```bash
ps auxw|grep [u]nfs
cat ~/.dinghy/machine-nfs-exports-dinghy
cat /usr/local/var/dinghy/dinghy-NFS.output
```

**Comment by joergd** [comment] 2016-02-29 19:48
Sure ....

    >: ps auxw|grep [u]nfs
    root            89145   0.0  0.1  2458220   4972   ??  S     8:32PM   0:00.43 /usr/local/sbin/unfsd -e /var/root/.dinghy/machine-nfs-exports-dinghy -n 19508 -m 19508 -l 172.16.52.1 -p -d
    root             1208   0.0  0.0  2459244    216   ??  Ss   Fri01PM   0:05.30 /usr/local/sbin/unfsd -e /Users/joerg/.dinghy/machine-nfs-exports-dinghy -n 19321 -m 19321 -l 172.16.52.1 -p -b -d

    >: cat ~/.dinghy/machine-nfs-exports-dinghy
    "/Users/joerg" 172.16.52.141(rw,all_squash,anonuid=501,anongid=20)

    >: cat /usr/local/var/dinghy/dinghy-NFS.output
    cat: /usr/local/var/dinghy/dinghy-NFS.output: No such file or directory

**Comment by codekitchen** [comment] 2016-02-29 19:51
Ah, it looks like you have some old NFS processes left over from the original bug. Kill those two processes (running as root so you'll need to sudo) and restart dinghy, hopefully that'll clear things up. (fingers crossed)

**Comment by joergd** [comment] 2016-02-29 19:55
No pity - same error. I made sure I did dinghy halt first, again looked for the nfs processes, killed them all off successfully, then did a dinghy up, and got the same error message as before ... :(

**Comment by codekitchen** [comment] 2016-03-01 15:59
Hm I'm not sure where the permission denied is coming from then. The NFS daemon only allows connections from the VM's IP, can you verify that the IP 172.16.52.141 in the config file is the IP of your VM? `dinghy ssh ifconfig` should show the IP.

**Comment by aaronlerch** [comment] 2016-03-05 20:19
I just hit the same problem. `sudo` (for me, on my mac) is not keeping the source environment variables. I use Boxen which does alter the `/etc/sudoers` file to alter behavior, I'm not sure if that's why it's not easily reproducible. But I did confirm that changing `cli/dinghy/unfs.rb` to include the `-E` command to `sudo` fixed the problem -- the problem here is `unfsd` is being started with `-e /var/root/.dinghy/machine-nfs-exports-dinghy` because the sudo'd version of dinghy is using the root user's home dir. But that config file is empty.

Here's the changes I made locally to test that it worked for me:

```
  def up
    if root?
      super
    else
      write_exports!
      puts starting_message
      system("sudo", "-E", "#{DINGHY}/bin/dinghy", "nfs", "start", port.to_s, machine.host_ip)
    end
  end

  def halt
    if root?
      super
    else
      puts stopping_message
      system("sudo", "-E", "#{DINGHY}/bin/dinghy", "nfs", "stop", "0", "0") # port and host_ip unused
    end
```

I'm not sure that's the ultimate solution, but it gets me over the hump here.

**Comment by aaronlerch** [comment] 2016-03-06 02:23
I confirmed it's the configuration that Boxen laid down by default in my sudoers file. @joergd I'm not sure what your local configuration is like, but try adding `Defaults env_keep+="HOME"` to your sudoers file to see if that makes a difference.

**Comment by codekitchen** [comment] 2016-03-09 19:55
Ah that's great information, thanks @aaronlerch . I could continue to fix these problems one-by-one but I think the fundamental problem here is trying to run a bunch of dinghy code under a sudo environment, with all the different ways that could break. I think I'll modify the main dinghy process to instead pass in the exact unfs command that needs to be run, and get rid of any other logic in the sudo'd sub-process. I was hesitant to do that when I first implemented this, but on further reflection I don't see any risk.

**Comment by aaronlerch** [comment] 2016-03-09 20:58
:+1: agreed

**Comment by codekitchen** [comment] 2016-03-15 16:29
OK, I've got a fix that just landed on master. I tested it as well as I could by removing HOME from my env_keep config, but if somebody else could install the dinghy prerelease and try it out that'd be great.

**Comment by gharwood1** [comment] 2016-03-22 02:38
@codekitchen, I am also set up with Boxen and this change worked for me. I didn't have to implement @aaronlerch's changes. I just installed the prerelease and all was well. Thanks!

**Comment by codekitchen** [comment] 2016-03-23 20:37
Great, thanks @gharwood1 . I'll close this once I cut a new release.

**Comment by codekitchen** [comment] 2016-03-29 18:00
ok this has been released, let me know if any further issues crop up with it

**Closed by codekitchen** 2016-03-29 18:00 UTC

**Comment by joergd** [comment] 2016-06-28 07:05
Sorry - FINALLY got a chance to work on this again. Yes - I just installed HEAD - and it works great - thank you!
