### ISSUE TITLE
Self-signed SSL for multiple subdomains?

### ISSUE THREAD

**Issue by Ghazgkull** [codekitchen/dinghy#203] opened 2016-08-17 20:06 UTC
Is it currently possible to enable SSL for multiple virtual hosts in dinghy?

Following the instructions on the [dinghy-http-proxy wiki](https://github.com/codekitchen/dinghy-http-proxy#ssl-support), I was able to quickly generate a self-signed cert that worked for a single domain like `www.foo.docker`. But things didn't work out when I then also tried to generate/use certs for subdomains like `api.foo.docker` and `cdn.foo.docker`.

I've tried generating a cert/key pair for each virtual host (`www.foo.docker.crt`, `api.foo.docker.crt`, etc). But it seemed like dinghy would always pick one cert to use for all subdomains? When visiting `www.foo.com`, for example, Chrome would complain that the cert name didn't match and in the details it would show the cert name as `cdn.foo.com`.

I also tried using a single cert with subject alt names, but I'd get the same kind of error. (It's entirely possible I just screwed this up... I'm a total novice with SSL.)

**Comment by codekitchen** [comment] 2016-08-20 03:23
This will work as long as you have all four of the following files in the right place:

- `www.foo.docker.crt`
- `www.foo.docker.key`
- `api.foo.docker.crt`
- `api.foo.docker.key`

Can you verify that's the case? Also, how are these hostnames defined? If you're using `VIRTUAL_HOST`, what exact values are you using, or are you using the auto-assigned naming?

**Comment by Ghazgkull** [comment] 2016-08-29 21:02
(Sorry for the slow reply.)

Yes, I can confirm that this is the setup we tried.

We have two containers running under three virtual hosts defined as: `VIRTUAL_HOST: www.antenna.docker, api.antenna.docker` and `VIRTUAL_HOST: cdn.antenna.docker`.

We also set up a crt/key pair for each of these using commands like `openssl req -x509 -newkey rsa:2048 -keyout cdn.antenna.docker.key \
-out cdn.antenna.docker.crt -days 365 -nodes \
-subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=cdn.antenna.docker"`

It works for one container, but not for the others. It looks like dinghy is just picking the first cert that matches and using that cert for all of the configured VIRTUAL_HOSTS. For example, I see the `cdn.antenna.docker` cert being served for`cdn.antenna.docker`, `www.antenna.docker`, and `api.antenna.docker`.

We had two developers set this up independently and both saw the same behavior.

**Comment by codekitchen** [comment] 2016-08-29 21:49
Hm that all sounds correct, but I haven't seen this problem elsewhere. Can you send over the dir listing of your certs dir `ls ~/.dinghy/certs` and the proxy's nginx config when these containers are running `docker exec -it dinghy_http_proxy cat /etc/nginx/conf.d/default.conf`. Maybe something there will give us a clue about what's different here.

**Comment by Ghazgkull** [comment] 2016-09-13 22:48
Here's the directory listing:
```
$ ls ~/.dinghy/certs
api.antenna.docker.crt	api.antenna.docker.key	cdn.antenna.docker.crt	cdn.antenna.docker.key	www.antenna.docker.crt	www.antenna.docker.key
```
And the nginx config:
```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
upstream  api.antenna.docker {
	server 172.17.0.9:8081;
}
server {
	server_name  api.antenna.docker;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 301 https:// api.antenna.docker$request_uri;
}
server {
	server_name  api.antenna.docker;
	listen 443 ssl;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/api.antenna.docker.crt;
	ssl_certificate_key /etc/nginx/certs/api.antenna.docker.key;
	add_header Strict-Transport-Security "max-age=31536000";
	location / {
		proxy_pass http://api.antenna.docker;
	}
}
server {
	server_name  api.antenna.docker;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
 	return 503 "Unknown HTTPS_METHOD redirect";
 	add_header Content-Type text/plain;
 }
upstream cdn.antenna.docker {
	server 172.17.0.5:8081;
}
server {
	server_name cdn.antenna.docker;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://cdn.antenna.docker$request_uri;
}
server {
	server_name cdn.antenna.docker;
	listen 443 ssl;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/cdn.antenna.docker.crt;
	ssl_certificate_key /etc/nginx/certs/cdn.antenna.docker.key;
	add_header Strict-Transport-Security "max-age=31536000";
	location / {
		proxy_pass http://cdn.antenna.docker;
	}
}
server {
	server_name cdn.antenna.docker;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
 	return 503 "Unknown HTTPS_METHOD redirect";
 	add_header Content-Type text/plain;
 }
upstream www.antenna.docker {
	server 172.17.0.9:8081;
}
server {
	server_name www.antenna.docker;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://www.antenna.docker$request_uri;
}
server {
	server_name www.antenna.docker;
	listen 443 ssl;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/www.antenna.docker.crt;
	ssl_certificate_key /etc/nginx/certs/www.antenna.docker.key;
	add_header Strict-Transport-Security "max-age=31536000";
	location / {
		proxy_pass http://www.antenna.docker;
	}
}
server {
	server_name www.antenna.docker;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
 	return 503 "Unknown HTTPS_METHOD redirect";
 	add_header Content-Type text/plain;
 }
```
And here is where Chrome complains that it's getting the wrong certificate: http://d.pr/i/55sU

**Comment by codekitchen** [comment] 2016-09-14 15:19
Yeah the config looks correct. Are you certain that the `www.antenna.docker.crt` file is correct? Maybe it's got the wrong CNAME in it. You could also use `openssl` or another tool to connect to https://www.antenna.docker and download the cert, and compare it to your `www.antenna.docker.crt` cert on disk, to verify if you're getting back the cert that you expect.

**Comment by Ghazgkull** [comment] 2016-09-14 15:22
Yep. I'm sure it's correct. Every time I try this, I'm creating new certs and starting from scratch (that's part of why it sometimes takes me so long to reply). Here are the commands I used to create the certs I tested with yesterday:

`openssl req -x509 -newkey rsa:2048 -keyout cdn.antenna.docker.key -out cdn.antenna.docker.crt -days 365 -nodes -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=cdn.antenna.docker"`

`openssl req -x509 -newkey rsa:2048 -keyout www.antenna.docker.key -out www.antenna.docker.crt -days 365 -nodes -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=www.antenna.docker"`

`openssl req -x509 -newkey rsa:2048 -keyout api.antenna.docker.key -out api.antenna.docker.crt -days 365 -nodes -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=api.antenna.docker"`

**Comment by Ghazgkull** [comment] 2016-09-14 15:27
And here's confirmation that the wrong cert is being served:

```
$ openssl s_client -showcerts -servername www.antenna.docker -connect www.antenna.docker:443 </dev/null
CONNECTED(00000003)
depth=0 /C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=cdn.antenna.docker
verify error:num=18:self signed certificate
verify return:1
depth=0 /C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=cdn.antenna.docker
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=cdn.antenna.docker
   i:/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=cdn.antenna.docker
-----BEGIN CERTIFICATE-----
MIIEQjCCAyqgAwIBAgIJAMa7YMp+BbFfMA0GCSqGSIb3DQEBBQUAMHMxCzAJBgNV
BAYTAlVTMQ8wDQYDVQQIEwZPcmVnb24xETAPBgNVBAcTCFBvcnRsYW5kMRUwEwYD
VQQKEwxDb21wYW55IE5hbWUxDDAKBgNVBAsTA09yZzEbMBkGA1UEAxMSY2RuLmFu
dGVubmEuZG9ja2VyMB4XDTE2MDkxNDE1MjQ1NVoXDTE3MDkxNDE1MjQ1NVowczEL
MAkGA1UEBhMCVVMxDzANBgNVBAgTBk9yZWdvbjERMA8GA1UEBxMIUG9ydGxhbmQx
FTATBgNVBAoTDENvbXBhbnkgTmFtZTEMMAoGA1UECxMDT3JnMRswGQYDVQQDExJj
ZG4uYW50ZW5uYS5kb2NrZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQCnbY8bEAKyR2MS2Zd9dVvf7Q5AW24u60UwItVWxlRvL6DOwiXJPULfDm7qyaPq
KY24hBGv34SvpYQ33ppC87qzXIN/CG27PtIqoNmAfDYvUIKa1OJbTPqYEzLHb1WO
//Ea79TG3Fms4uuY+/ECGJrTWG/Ylkc93SGj4BckSdiNSsC0ap2hhduf9v/Ia9K8
XV3uZeR+pphx5Vai1ZjibA1CfpF9WI9KMLeJdsr2Kp1VnliMWavJRFcdB5Wjn8jI
0YWIwPqBxnKL9BmWMPL/N17P3LLvBlK4KInnQl9EYcxAwLXPT6KsDkDFHn3pIrSS
6MvhxHt5drIfEIj3E+G0XxIFAgMBAAGjgdgwgdUwHQYDVR0OBBYEFAw9QdLP45cf
qGEBoaweg341MQhXMIGlBgNVHSMEgZ0wgZqAFAw9QdLP45cfqGEBoaweg341MQhX
oXekdTBzMQswCQYDVQQGEwJVUzEPMA0GA1UECBMGT3JlZ29uMREwDwYDVQQHEwhQ
b3J0bGFuZDEVMBMGA1UEChMMQ29tcGFueSBOYW1lMQwwCgYDVQQLEwNPcmcxGzAZ
BgNVBAMTEmNkbi5hbnRlbm5hLmRvY2tlcoIJAMa7YMp+BbFfMAwGA1UdEwQFMAMB
Af8wDQYJKoZIhvcNAQEFBQADggEBAEqy1AHXKUQ83bY9oBbJnYXXCAn5N5PP6mVW
AbM6DAeH1O7tZzZsb6qqynVamBOlbxnrm2BcwIg3F8LZZuBpk2+2CYp/xUBrGIzr
SB15/K3q8VQFvoATS5D7By6xF0tYLDvv/Kqlv6WOWYMyrmeiEDqVAXftU8s9/UCe
/Q75zLvsR/SDR208MY+7gdIdoEaP+18XLx9AxYi28cyAp/2OIAtkRKTRE55GSS1b
ySICsMKNiySdHl0Mi7+tG+Fytbc32z2iw3FzhSbclXeMzi42J/G+y7Uh1gqfc88N
a+pZVJXUiC8ghxoYvQTEd1Wdi1aCSmyp7xBR7qIrUWCYrfkYRdQ=
-----END CERTIFICATE-----
---
Server certificate
subject=/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=cdn.antenna.docker
issuer=/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=cdn.antenna.docker
---
No client certificate CA names sent
---
SSL handshake has read 1972 bytes and written 325 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES128-SHA
    Session-ID: BCB0A0DE94BD01DB657715629702DF1E1F513B9154AF3A9A8B62148C7E139F54
    Session-ID-ctx: 
    Master-Key: EE6950F9DB564088B24076F661F82E27A1AD9A1EC3ED7D17A7A8B028596553425DC9E11DA28641BA0095B607839EBD25
    Key-Arg   : None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 2a 07 9a 3d 85 f3 85 8e-2d 93 8d 70 12 63 95 c6   *..=....-..p.c..
    0010 - 6e a8 55 67 08 9c db 4e-a2 01 17 54 ab 1e 81 31   n.Ug...N...T...1
    0020 - 52 cf c9 56 5a c3 00 8d-2d d2 ba 02 59 43 4a 46   R..VZ...-...YCJF
    0030 - 5b d6 6e 06 32 aa 30 7c-fd e8 08 9e 7c e7 6e 5e   [.n.2.0|....|.n^
    0040 - 6e 66 9f 9d 72 12 8a bd-16 7e 70 7e f9 3d 70 68   nf..r....~p~.=ph
    0050 - 51 ca cb 75 2d 15 19 8f-19 9b a8 28 8d 0a 94 a3   Q..u-......(....
    0060 - a5 45 6c 53 53 df 1a 1e-c4 b0 93 cf 08 56 36 17   .ElSS........V6.
    0070 - a5 d6 3f 7c a4 f2 4e ae-82 b0 cf 59 40 81 cc ad   ..?|..N....Y@...
    0080 - 00 43 bc 45 69 05 9d af-5b fc 06 06 86 45 74 79   .C.Ei...[....Ety
    0090 - 90 65 94 e4 73 60 83 cb-82 0f b5 f5 ff b7 dc eb   .e..s`..........
    00a0 - 12 60 9f 9c 32 86 80 b6-a6 55 a8 f2 01 9b d7 31   .`..2....U.....1
    00b0 - ff 47 bd 9e 99 fb a2 3f-e0 f9 4f 91 ae aa 66 d3   .G.....?..O...f.

    Start Time: 1473866796
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
DONE
```

**Comment by codekitchen** [comment] 2016-09-14 15:31
Hm I wonder if nginx's SNI support isn't functioning for some reason. I'll try to repro the problem.

**Comment by codekitchen** [comment] 2016-09-14 15:43
I wasn't able to reproduce the problem on the latest dinghy, using your same `openssl` commands to generate the `cdn.antenna.docker` and `www.antenna.docker` certs/keys. Both chrome and openssl are served the correct cert for each of those hostnames.

However, I can tell from the nginx config that you pasted, that you are using an older version of dinghy and dinghy-http-proxy.  It's quite possible this doesn't work in that older version -- I update to the newest upstream jwilder/nginx-proxy with each release. So I'd suggest a [dinghy upgrade](https://github.com/codekitchen/dinghy#upgrading) as the next thing to try.

**Comment by Ghazgkull** [comment] 2016-09-14 16:20
We hit the same problem after running `dinghy upgrade`, but noticed that it installed `dinghy-http-proxy` v2.5.0. Trying the latest (2.5.2) now.

**Comment by codekitchen** [comment] 2016-09-14 16:23
I'm running 2.5.0 as well, 2.5.2 hasn't been part of a dinghy release yet.

**Comment by codekitchen** [comment] 2016-09-14 16:33
Here's a shell session showing what I did, so we can be sure we're comparing apples to apples: https://gist.github.com/codekitchen/f1a28015672d2dcfe3ee1980cf6e7ef2

I'm not sure what else could be going on here, so hopefully you see something in there that's different from what you're doing. 😄

**Comment by Ghazgkull** [comment] 2016-09-14 16:44
Yep, what you're doing matches our setup.

We just tried upgrading dinghy to the latest HEAD version (which pulled 2.5.2), and now it just worked for the first time.

**Comment by codekitchen** [comment] 2016-09-14 16:51
Hm that sounds like we're missing something, since I was successful with 2.5.0. But, that's great that it's working.

**Comment by yenif** [comment] 2016-09-14 18:53
Pretty sure codekitchen/dinghy-http-proxy@de1403df79cda99a4372c11c1aa45af7151f8979 is why it works in 1.5.2. Our VIRTUAL_HOST is set to "www.antenna.docker, api.antenna.docker" which before that commit produced the following block with an extra space in the 301 redirect

```
server {
	server_name  api.antenna.docker;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 301 https:// api.antenna.docker$request_uri;
}
```

**Comment by codekitchen** [comment] 2016-09-14 19:14
Oh that's interesting, so that was fixed by accident. It looks like that does indirectly break things -- `docker logs dinghy_http_proxy` when using that config will show `Error running notify command: /app/reload-nginx, exit status 1`, I'm sure because nginx rejects the config file as invalid. So the final full config wasn't even getting loaded into nginx.

Glad that mystery is solved, I'm going to close this. New version of dinghy should be released soon.

**Closed by codekitchen** 2016-09-14 19:14 UTC
