### ISSUE TITLE
fails: dinghy create --provider vmware_fusion

### ISSUE THREAD

**Issue by Morriz** [codekitchen/dinghy#183] opened 2016-05-20 11:16 UTC
I believe you solved this (from reading some issues), but I see no solution using docker-machine anywhere. Could you please provide a valid example with docker-machine using the dinghy image?

**Comment by Morriz** [comment] 2016-05-20 14:45
I was only able to install with sudo for -d vmwarefusion, and had to move and chown the artifacts. But now the containers are started with user root. Any idea how to change that?

**Comment by codekitchen** [comment] 2016-05-20 15:27
Can you describe more about what fails? I'm not really clear on what the issue is. What does "Could you please provide a valid example with docker-machine using the dinghy image" mean?

**Comment by Morriz** [comment] 2016-05-20 15:50
Nevermind about that/ The problem is with the vmwarefusion plugin I believe. I can only run `dinghy create` as root, and have to fix stuff afterwards. That the containers start as root is also normal I understand. I seem to have the same issue as #157, and get chown not permitted errors on npm install.

Any idea if that is related to your setup?

**Comment by codekitchen** [comment] 2016-05-20 16:28
You shouldn't need to run `docker-machine create` or `dinghy create` as root, have you filed an issue with the vmwarefusion project?

As outlined in #157 you'll want to either configure your container to not run as root, or configure your container to not use the NFS share for the `node_modules` directory. These days we typically use a docker volume for external code dirs such as `node_modules` and ruby bundler's `vendor/bundle`.

**Comment by codekitchen** [comment] 2016-09-01 16:20
I'm going to close this, as I don't see anything else that's actionable here. Please file a new issue if you are still experiencing problems.

**Closed by codekitchen** 2016-09-01 16:20 UTC
