### ISSUE TITLE
Files not Syncing - NFS.output shows "unable to send RPC reply"

### ISSUE THREAD

**Issue by gmeans** [codekitchen/dinghy#182] opened 2016-05-14 15:26 UTC
I have been using Dinghy for a while, but just recently noticed my files aren't syncing over. I'm sorry I'm not entirely clear what change to my system prompted this.

I have upgraded everything:

- OSX 10.11.4
- Dinghy 4.3.2
- docker-machine version 0.7.0, build a650a40
- Docker version 1.11.0, build 4dc5990

Everything starts up and functions fine, but updates to files aren't syncing over to the containers anymore. When I look at dinghy-NFS.output I see this:

UNFS3 unfsd 0.9.22 (C) 2006, Pascal Schmidt <unfs3-server@ewetel.net>
/Users/gmeans: ip 192.168.99.100 mask 255.255.255.255 options 6
unable to send RPC reply
unable to send RPC reply
unable to send RPC reply
unable to send RPC reply
unable to send RPC reply
unable to send RPC reply
unable to send RPC reply
unable to send RPC reply
unable to send RPC reply

Any ideas? Thanks!

**Comment by gmeans** [comment] 2016-05-14 18:19
Quick update, I've tried this with both the xhyve and virtual box (w/ extension pack) providers creating fresh machines. I also have the Firewall Disabled thinking maybe somehow a port was blocked. (I see unfsd in the app listing under System Preferences).

Everything starts up fine, but as soon as I update a file that should sync over I see the "unable to send RPC reply" messages show up in the log.

**Comment by codekitchen** [comment] 2016-05-16 18:10
Hm I had this happen to a co-worker once, but it was caused by VirtualBox networking bugginess -- rebooting his laptop fixed it. If it's affecting xhyve as well that sounds like something different. It doesn't sound like a firewall issue, since the initial `mount` command didn't fail, so at least some network traffic is getting through.

If you `dinghy ssh` into the VM and look at the logs under `/var/log` do you see anything that looks relevant?

**Comment by codekitchen** [comment] 2016-09-01 16:21
Hi @gmeans is this still an issue? I'm going to close it but feel free to re-open.

**Closed by codekitchen** 2016-09-01 16:21 UTC

**Comment by gmeans** [comment] 2016-09-01 19:24
Hi @codekitchen unfortunately I just switched back to standard docker-machine with the Virtual Box extensions installed. That worked for me so I moved off of Dinghy.

It was probably something related to my configuration, so I think this is fine to close.

Thanks!
