### ISSUE TITLE
"Mounting NFS" step taking 3+ minutes

### ISSUE THREAD

**Issue by egyptianbman** [codekitchen/dinghy#63] opened 2015-08-30 07:02 UTC
Hello,

I would submit a PR for this but I'm not very familiar with Ruby.  When I start the VM (on `machine` as well as `master` branches), dinghy hangs on mounting NFS.  By that I mean it takes several minutes for it to mount and at times would fail causing partial `up` status.

I've finally found a fix for this inspired by https://github.com/boot2docker/boot2docker/issues/581#issuecomment-127972657.  I've found that adding:
```
/Users/{USER} -mapall={USER}:staff {VM_IP}
```
to `/etc/exports` makes the nfs mount instantaneous.

`/etc/exports` didn't exist for me and I'd guess for 99.9% of people out there it won't, but for the sake of safety I'd say the code should do something along the lines of the following:

1. Check to see if `/etc/exports` exists.  If it doesn't create it with the line above.
2. If it does exist, check if the line above exists (maybe surround with a dinghy-specific comment above and below the command that can allow you to replace the block?)
3. `sudo nfsd stop && sudo nfsd start`
4. mount and profit.

I'm using virtualbox.  Let me know if you have any questions or need me to provide any more info.  Thanks again for your awesome work!

**Comment by codekitchen** [comment] 2015-08-31 20:11
Thanks for the investigation -- dinghy is not using the built-in `nfsd` for a few different reasons, which is why dinghy doesn't touch the `/etc/exports` file. I'm happy to help you track down why the `unfsd` daemon that dinghy uses isn't behaving for you, but we're not going to switch over to the system `nfsd` at this time.

**Comment by egyptianbman** [comment] 2015-08-31 20:44
I disabled `nfsd` and ran three tests (with a `dinghy halt` in between):

#### Test 1
```bash
$ time dinghy up --proxy --fsevents
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/beshoygirgis
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/ssh.rb:23:in `run': Error executing command: ["sudo umount /Users || true"] (Ssh::CommandFailed)
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:76:in `ssh'
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:69:in `mount'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:181:in `start_services'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:78:in `up'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:6:in `<main>'
[2]    9732 exit 1     dinghy up --proxy --fsevents
dinghy up --proxy --fsevents  0.61s user 0.52s system 1% cpu 57.319 total
```

#### Test 2
```
$ time dinghy up --proxy --fsevents
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/beshoygirgis
Starting the FsEvents daemon
Starting the DNS daemon
Starting the HTTP proxy
539c74a6b5128bcad9c027752d95cb943a61e6537a45d9de0699530d24b9efe8
To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.99.100:2376
    export DOCKER_CERT_PATH=/Users/beshoygirgis/.docker/machine/machines/dinghy
    export DOCKER_TLS_VERIFY=1
    export DOCKER_MACHINE_NAME=dinghy
dinghy up --proxy --fsevents  1.35s user 0.74s system 5% cpu 35.696 total
```

#### Test 3
```
$ time dinghy up --proxy --fsevents
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/beshoygirgis
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/ssh.rb:23:in `run': Error executing command: ["sudo umount /Users || true"] (Ssh::CommandFailed)
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:76:in `ssh'
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:69:in `mount'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:181:in `start_services'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:78:in `up'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:6:in `<main>'
[2]    10105 exit 1     dinghy up --proxy --fsevents
dinghy up --proxy --fsevents  0.61s user 0.52s system 1% cpu 57.110 total
```

Disabling `nfsd` seems to have made it faster -- it doesn't take several minutes to load but at times it crashes.

**Comment by egyptianbman** [comment] 2015-09-02 19:53
Something must have been cached or running when I did my previous tests. After reboot, my system went back to taking much longer to mount:

#### Test 1
```bash
$ nfsd status
nfsd service is disabled
nfsd is not running

$ time dinghy up --proxy --fsevents
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/beshoygirgis
Starting the FsEvents daemon
Starting the DNS daemon
Starting the HTTP proxy
9acd048a4672aaf4818f1f657d7a99388b39568422592104ac69c9a45fafce17
To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.99.100:2376
    export DOCKER_CERT_PATH=/Users/beshoygirgis/.docker/machine/machines/dinghy
    export DOCKER_TLS_VERIFY=1
    export DOCKER_MACHINE_NAME=dinghy
dinghy up --proxy --fsevents  1.33s user 0.73s system 0% cpu 5:57.24 total
```

#### Test 2
```bash
$ time dinghy up --proxy --fsevents
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/beshoygirgis
Starting the FsEvents daemon
Starting the DNS daemon
Starting the HTTP proxy
f523dec61ce96f67c4b5b20803619f2396e6b0246fec87d2bd29e968c2245d86
To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.99.100:2376
    export DOCKER_CERT_PATH=/Users/beshoygirgis/.docker/machine/machines/dinghy
    export DOCKER_TLS_VERIFY=1
    export DOCKER_MACHINE_NAME=dinghy
dinghy up --proxy --fsevents  1.23s user 0.67s system 0% cpu 4:49.33 total
```

#### Test 3
```bash
$ time dinghy up --proxy --fsevents
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/unfs.rb:25:in `sleep': execution expired (Timeout::Error)
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/unfs.rb:25:in `block in wait_for_unfs'
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/unfs.rb:22:in `wait_for_unfs'
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/unfs.rb:18:in `up'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:180:in `start_services'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:78:in `up'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:6:in `<main>'
[2]    24179 exit 1     dinghy up --proxy --fsevents
dinghy up --proxy --fsevents  0.87s user 0.74s system 2% cpu 1:05.77 total
```

**Comment by codekitchen** [comment] 2015-09-02 20:23
Hm I don't think enabling/disabling `nfsd` will have any affect, the NFS setup that dinghy is using is completely separated from the system daemon.

When it takes 4+ minutes to come up, where is that time mostly spent? Is it on the `Waiting for NFS daemon...` step? That would surprise me, as that step should have a 20 second timeout before it fails, but maybe something isn't working right there.

**Comment by egyptianbman** [comment] 2015-09-02 21:33
I posted the bit about `nfsd` to confirm it's not getting in the way of the test.

The hang is on the `Mounting NFS /Users/beshoygirgis`.  I think the timeout you mention is what's causing the `Timeout::Error`.

**Comment by codekitchen** [comment] 2015-09-02 21:35
Yep it is, my question is if it's hanging on that step for 4 minutes or more, when the timeout is set to 20 seconds. That's very odd.

**Comment by egyptianbman** [comment] 2015-09-02 21:37
You have a timeout on the `Mounting` step, not just the `Waiting for NFS`?

**Comment by codekitchen** [comment] 2015-09-02 21:46
Ah, I misread your last message, my bad.

So you are seeing two separate problems, sometimes it times out waiting for the `unfsd` daemon to start up and begin listening for connections, sometimes that succeeds but it takes an extremely long time for the mount command to finish. Both could certainly be explained by something triggering poor performance in `unfsd`, or it could be related to the virtual network interface.

Does the NFS share have acceptable performance once it's mounted, or is accessing files over the share inside the VM slow as well? You can `dinghy ssh` into the vm and dig around in `/Users/beshoygirgis` to test that out.

It might be worthwhile to try mounting the NFS share back onto another location on the host, to rule out the virtual network, though you'd need to modify `/Library/LaunchDaemons/dinghy.unfs.plist` and `~/.dinghy/machine-nfs-exports-dinghy` to allow connecting from your host IP.

**Comment by egyptianbman** [comment] 2015-09-02 22:23
The difference in speed, NFS vs root:
```bash
docker@dinghy:/Users/beshoygirgis$ dd if=/dev/zero of=testfile bs=8k count=10000; sync;
10000+0 records in
10000+0 records out
81920000 bytes (78.1MB) copied, 2.580762 seconds, 30.3MB/s

docker@dinghy:~$ dd if=/dev/zero of=testfile bs=8k count=10000; sync;
10000+0 records in
10000+0 records out
81920000 bytes (78.1MB) copied, 0.028152 seconds, 2.7GB/s
```

The NFS seems to be sufficient in speed once it's up and running (much faster than before using the `machine` branch.  I'm not sure how to mount the home directory on OSX using NFS.  Can you provide an example command?

**Comment by codekitchen** [comment] 2015-10-14 15:24
Sure, I see similar speeds if I run the same `dd` command -- 1.5s over the NFS mount, and a couple microseconds directly on the VM drive.

That doesn't seem surprising to me though, NFS adds a lot of overhead, but it's still orders of magnitude faster than built-in virtualbox file sharing. It's been plenty fast for the things we use dinghy for, is it not performant enough for your local development needs?

**Comment by codekitchen** [comment] 2015-10-14 15:26
Oh, again I've misread, sorry. I've forgotten all the context around this discussion in the last month. You weren't saying it wasn't fast enough, just providing data.

**Comment by codekitchen** [comment] 2015-10-14 15:35
The `Timeout::Error` is related to `launchd` reporting success when it didn't really succeed, we have an open ticket to switch to managing the daemons ourselves to remove the `launchd` usage.

I don't have any good theory yet for why you'd be seeing the mount command take minutes to complete, but then NFS run at the normal speed once it finally does mount. I doubt it's related to the network interface if things work fine once it's done.

**Comment by egyptianbman** [comment] 2015-10-15 00:54
Welp.. I just ran into some oddity that was causing the dinghy vm to crash on boot.  Turns out the Virtualbox kernel got messed up somehow due to the os upgrade.  Upon reinstalling Virtualbox, dinghy seems to boot up promptly now.

**Comment by codekitchen** [comment] 2016-01-04 16:24
A lot of the issues with this are because launchd reports success even if the daemon fails to launch (apparently this is by design). Because of all the issues with using/abusing launchd the way we were, we've moved to our own daemon management code in the newest v4.1.0 release of dinghy. I'm going to close this, we'll handle any similar problems on the newest release as a new issue.

**Closed by codekitchen** 2016-01-04 16:24 UTC
